language: haskell

ghc:
    - 7.4
    - 7.6
    - 7.8

before_install:
    - git clone https://github.com/augustss/geniplate.git

install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - cabal update
    - cabal install alex happy
    - alex --version
    - happy --version
    - cabal install bnfc geniplate/ 'mtl < 2.2' # or set transformers bound

before_script:
    - true

script:
    - ./make_parser.sh
    - cabal install tip-lib/ tip-haskell-frontend/
    - tip-ghc examples/Int.hs
    - tip-parser <(tip-ghc examples/Int.hs)
    - tip-ghc examples/Case.hs
    - tip-parser <(tip-ghc examples/Case.hs)

