language: haskell

ghc:
    - 7.4
    - 7.6
    - 7.8

before_install:
    - git clone https://github.com/augustss/geniplate.git

install:
    - cabal install geniplate/ 'mtl < 2.2' # or set transformers bound

before_script:
    - true

script:
    - cabal install tip-lib/ tip-haskell-frontend/
