language: haskell

ghc:
    - 7.4
    - 7.6
    - 7.8

install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - cabal update
    - cabal install alex happy
    - alex --version
    - happy --version
    - cabal install bnfc

before_script:
    - true

script:
    - ./make_parser.sh
    - cabal install tip-lib/ tip-haskell-frontend/
    - tip-ghc examples/Int.hs
    - tip <(tip-ghc examples/Int.hs)
    - tip-ghc examples/Case.hs
    - tip <(tip-ghc examples/Case.hs)
    - tip-ghc examples/Props.hs
    - tip <(tip-ghc examples/Props.hs)

